name: A workflow for my hello world file
on: push
jobs:
  build:
    name: Hello world action from this yaml file
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v1
      -uses: ./action-a
        with:
          MY_NAME: "Stealthfish"
          